/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _authedRouteRouteImport } from './routes/(_authed)/route'
import { Route as _authedIndexRouteImport } from './routes/(_authed)/index'
import { Route as _authedAccountIndexRouteImport } from './routes/(_authed)/account/index'
import { Route as _authedTasksIndexRouteImport } from './routes/(_authed)/tasks/index'
import { Route as PublicAuthDevTokenRouteImport } from './routes/_public/auth/dev-token'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth/callback'
import { Route as PublicSsoRelayRouteImport } from './routes/_public/sso/relay'
import { Route as PublicWhatsNewIndexRouteImport } from './routes/_public/whats-new/index'
import { Route as PublicWhatsNewVersionRouteImport } from './routes/_public/whats-new/$version'
import { Route as _authedPSlugIndexRouteImport } from './routes/(_authed)/p/$slug/index'
import { Route as _authedPSlugBacklogRouteImport } from './routes/(_authed)/p/$slug/backlog'
import { Route as _authedPSlugEpicsRouteImport } from './routes/(_authed)/p/$slug/epics'
import { Route as _authedPSlugMembersRouteImport } from './routes/(_authed)/p/$slug/members'
import { Route as _authedPSlugSettingsRouteImport } from './routes/(_authed)/p/$slug/settings'
import { Route as _authedPSlugVelocityRouteImport } from './routes/(_authed)/p/$slug/velocity'
import { Route as _authedProjectsSlugIndexRouteImport } from './routes/(_authed)/projects/$slug/index'
import { Route as _authedProjectsSlugBacklogRouteImport } from './routes/(_authed)/projects/$slug/backlog'
import { Route as _authedProjectsSlugEpicsRouteImport } from './routes/(_authed)/projects/$slug/epics'
import { Route as _authedProjectsSlugMembersRouteImport } from './routes/(_authed)/projects/$slug/members'
import { Route as _authedProjectsSlugSettingsRouteRouteImport } from './routes/(_authed)/projects/$slug/settings/route'
import { Route as _authedProjectsSlugVelocityRouteImport } from './routes/(_authed)/projects/$slug/velocity'
import { Route as _authedSStoryIdIndexRouteImport } from './routes/(_authed)/s/$storyId/index'
import { Route as PublicAuthAtprotoCallbackRouteImport } from './routes/_public/auth/atproto/callback'
import { Route as PublicAuthGoogleCallbackRouteImport } from './routes/_public/auth/google/callback'
import { Route as _authedPSlugBoardIndexRouteImport } from './routes/(_authed)/p/$slug/board/index'
import { Route as _authedPSlugBoardStoryRefRouteImport } from './routes/(_authed)/p/$slug/board/$storyRef'
import { Route as _authedProjectsSlugBoardIndexRouteImport } from './routes/(_authed)/projects/$slug/board/index'
import { Route as _authedProjectsSlugBoardStoryRefRouteImport } from './routes/(_authed)/projects/$slug/board/$storyRef'
import { Route as _authedProjectsSlugSettingsIndexRouteImport } from './routes/(_authed)/projects/$slug/settings/index'
import { Route as _authedProjectsSlugSettingsDangerRouteImport } from './routes/(_authed)/projects/$slug/settings/danger'
import { Route as _authedProjectsSlugSettingsDataRouteImport } from './routes/(_authed)/projects/$slug/settings/data'
import { Route as _authedProjectsSlugSettingsGeneralRouteImport } from './routes/(_authed)/projects/$slug/settings/general'
import { Route as _authedProjectsSlugSettingsIntegrationsRouteImport } from './routes/(_authed)/projects/$slug/settings/integrations'
import { Route as _authedProjectsSlugSettingsNotificationsRouteImport } from './routes/(_authed)/projects/$slug/settings/notifications'
import { Route as _authedProjectsSlugSettingsOwnershipRouteImport } from './routes/(_authed)/projects/$slug/settings/ownership'
import { Route as _authedProjectsSlugSettingsWebhooksRouteImport } from './routes/(_authed)/projects/$slug/settings/webhooks'

const _authedRouteRoute = _authedRouteRouteImport.update({
  id: '/(_authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedIndexRoute = _authedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedAccountIndexRoute = _authedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedTasksIndexRoute = _authedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const PublicAuthDevTokenRoute = PublicAuthDevTokenRouteImport.update({
  id: '/_public/auth/dev-token',
  path: '/auth/dev-token',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/_public/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSsoRelayRoute = PublicSsoRelayRouteImport.update({
  id: '/_public/sso/relay',
  path: '/sso/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWhatsNewIndexRoute = PublicWhatsNewIndexRouteImport.update({
  id: '/_public/whats-new/',
  path: '/whats-new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWhatsNewVersionRoute = PublicWhatsNewVersionRouteImport.update({
  id: '/_public/whats-new/$version',
  path: '/whats-new/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedPSlugIndexRoute = _authedPSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugBacklogRoute = _authedPSlugBacklogRouteImport.update({
  id: '/p/$slug/backlog',
  path: '/p/$slug/backlog',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugEpicsRoute = _authedPSlugEpicsRouteImport.update({
  id: '/p/$slug/epics',
  path: '/p/$slug/epics',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugMembersRoute = _authedPSlugMembersRouteImport.update({
  id: '/p/$slug/members',
  path: '/p/$slug/members',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugSettingsRoute = _authedPSlugSettingsRouteImport.update({
  id: '/p/$slug/settings',
  path: '/p/$slug/settings',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugVelocityRoute = _authedPSlugVelocityRouteImport.update({
  id: '/p/$slug/velocity',
  path: '/p/$slug/velocity',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedProjectsSlugIndexRoute =
  _authedProjectsSlugIndexRouteImport.update({
    id: '/projects/$slug/',
    path: '/projects/$slug/',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugBacklogRoute =
  _authedProjectsSlugBacklogRouteImport.update({
    id: '/projects/$slug/backlog',
    path: '/projects/$slug/backlog',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugEpicsRoute =
  _authedProjectsSlugEpicsRouteImport.update({
    id: '/projects/$slug/epics',
    path: '/projects/$slug/epics',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugMembersRoute =
  _authedProjectsSlugMembersRouteImport.update({
    id: '/projects/$slug/members',
    path: '/projects/$slug/members',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugSettingsRouteRoute =
  _authedProjectsSlugSettingsRouteRouteImport.update({
    id: '/projects/$slug/settings',
    path: '/projects/$slug/settings',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugVelocityRoute =
  _authedProjectsSlugVelocityRouteImport.update({
    id: '/projects/$slug/velocity',
    path: '/projects/$slug/velocity',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedSStoryIdIndexRoute = _authedSStoryIdIndexRouteImport.update({
  id: '/s/$storyId/',
  path: '/s/$storyId/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const PublicAuthAtprotoCallbackRoute =
  PublicAuthAtprotoCallbackRouteImport.update({
    id: '/_public/auth/atproto/callback',
    path: '/auth/atproto/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicAuthGoogleCallbackRoute =
  PublicAuthGoogleCallbackRouteImport.update({
    id: '/_public/auth/google/callback',
    path: '/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const _authedPSlugBoardIndexRoute = _authedPSlugBoardIndexRouteImport.update({
  id: '/p/$slug/board/',
  path: '/p/$slug/board/',
  getParentRoute: () => _authedRouteRoute,
} as any)
const _authedPSlugBoardStoryRefRoute =
  _authedPSlugBoardStoryRefRouteImport.update({
    id: '/p/$slug/board/$storyRef',
    path: '/p/$slug/board/$storyRef',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugBoardIndexRoute =
  _authedProjectsSlugBoardIndexRouteImport.update({
    id: '/projects/$slug/board/',
    path: '/projects/$slug/board/',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugBoardStoryRefRoute =
  _authedProjectsSlugBoardStoryRefRouteImport.update({
    id: '/projects/$slug/board/$storyRef',
    path: '/projects/$slug/board/$storyRef',
    getParentRoute: () => _authedRouteRoute,
  } as any)
const _authedProjectsSlugSettingsIndexRoute =
  _authedProjectsSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsDangerRoute =
  _authedProjectsSlugSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsDataRoute =
  _authedProjectsSlugSettingsDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsGeneralRoute =
  _authedProjectsSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsIntegrationsRoute =
  _authedProjectsSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsNotificationsRoute =
  _authedProjectsSlugSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsOwnershipRoute =
  _authedProjectsSlugSettingsOwnershipRouteImport.update({
    id: '/ownership',
    path: '/ownership',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)
const _authedProjectsSlugSettingsWebhooksRoute =
  _authedProjectsSlugSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => _authedProjectsSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _authedIndexRoute
  '/auth/dev-token': typeof PublicAuthDevTokenRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/sso/relay': typeof PublicSsoRelayRoute
  '/whats-new/$version': typeof PublicWhatsNewVersionRoute
  '/account/': typeof _authedAccountIndexRoute
  '/tasks/': typeof _authedTasksIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/whats-new/': typeof PublicWhatsNewIndexRoute
  '/projects/$slug/settings': typeof _authedProjectsSlugSettingsRouteRouteWithChildren
  '/p/$slug/backlog': typeof _authedPSlugBacklogRoute
  '/p/$slug/epics': typeof _authedPSlugEpicsRoute
  '/p/$slug/members': typeof _authedPSlugMembersRoute
  '/p/$slug/settings': typeof _authedPSlugSettingsRoute
  '/p/$slug/velocity': typeof _authedPSlugVelocityRoute
  '/projects/$slug/backlog': typeof _authedProjectsSlugBacklogRoute
  '/projects/$slug/epics': typeof _authedProjectsSlugEpicsRoute
  '/projects/$slug/members': typeof _authedProjectsSlugMembersRoute
  '/projects/$slug/velocity': typeof _authedProjectsSlugVelocityRoute
  '/auth/atproto/callback': typeof PublicAuthAtprotoCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/p/$slug/': typeof _authedPSlugIndexRoute
  '/projects/$slug/': typeof _authedProjectsSlugIndexRoute
  '/s/$storyId/': typeof _authedSStoryIdIndexRoute
  '/p/$slug/board/$storyRef': typeof _authedPSlugBoardStoryRefRoute
  '/projects/$slug/board/$storyRef': typeof _authedProjectsSlugBoardStoryRefRoute
  '/projects/$slug/settings/danger': typeof _authedProjectsSlugSettingsDangerRoute
  '/projects/$slug/settings/data': typeof _authedProjectsSlugSettingsDataRoute
  '/projects/$slug/settings/general': typeof _authedProjectsSlugSettingsGeneralRoute
  '/projects/$slug/settings/integrations': typeof _authedProjectsSlugSettingsIntegrationsRoute
  '/projects/$slug/settings/notifications': typeof _authedProjectsSlugSettingsNotificationsRoute
  '/projects/$slug/settings/ownership': typeof _authedProjectsSlugSettingsOwnershipRoute
  '/projects/$slug/settings/webhooks': typeof _authedProjectsSlugSettingsWebhooksRoute
  '/p/$slug/board/': typeof _authedPSlugBoardIndexRoute
  '/projects/$slug/board/': typeof _authedProjectsSlugBoardIndexRoute
  '/projects/$slug/settings/': typeof _authedProjectsSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _authedIndexRoute
  '/auth/dev-token': typeof PublicAuthDevTokenRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
  '/sso/relay': typeof PublicSsoRelayRoute
  '/whats-new/$version': typeof PublicWhatsNewVersionRoute
  '/account': typeof _authedAccountIndexRoute
  '/tasks': typeof _authedTasksIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/whats-new': typeof PublicWhatsNewIndexRoute
  '/p/$slug/backlog': typeof _authedPSlugBacklogRoute
  '/p/$slug/epics': typeof _authedPSlugEpicsRoute
  '/p/$slug/members': typeof _authedPSlugMembersRoute
  '/p/$slug/settings': typeof _authedPSlugSettingsRoute
  '/p/$slug/velocity': typeof _authedPSlugVelocityRoute
  '/projects/$slug/backlog': typeof _authedProjectsSlugBacklogRoute
  '/projects/$slug/epics': typeof _authedProjectsSlugEpicsRoute
  '/projects/$slug/members': typeof _authedProjectsSlugMembersRoute
  '/projects/$slug/velocity': typeof _authedProjectsSlugVelocityRoute
  '/auth/atproto/callback': typeof PublicAuthAtprotoCallbackRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/p/$slug': typeof _authedPSlugIndexRoute
  '/projects/$slug': typeof _authedProjectsSlugIndexRoute
  '/s/$storyId': typeof _authedSStoryIdIndexRoute
  '/p/$slug/board/$storyRef': typeof _authedPSlugBoardStoryRefRoute
  '/projects/$slug/board/$storyRef': typeof _authedProjectsSlugBoardStoryRefRoute
  '/projects/$slug/settings/danger': typeof _authedProjectsSlugSettingsDangerRoute
  '/projects/$slug/settings/data': typeof _authedProjectsSlugSettingsDataRoute
  '/projects/$slug/settings/general': typeof _authedProjectsSlugSettingsGeneralRoute
  '/projects/$slug/settings/integrations': typeof _authedProjectsSlugSettingsIntegrationsRoute
  '/projects/$slug/settings/notifications': typeof _authedProjectsSlugSettingsNotificationsRoute
  '/projects/$slug/settings/ownership': typeof _authedProjectsSlugSettingsOwnershipRoute
  '/projects/$slug/settings/webhooks': typeof _authedProjectsSlugSettingsWebhooksRoute
  '/p/$slug/board': typeof _authedPSlugBoardIndexRoute
  '/projects/$slug/board': typeof _authedProjectsSlugBoardIndexRoute
  '/projects/$slug/settings': typeof _authedProjectsSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(_authed)': typeof _authedRouteRouteWithChildren
  '/(_authed)/': typeof _authedIndexRoute
  '/_public/auth/dev-token': typeof PublicAuthDevTokenRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
  '/_public/sso/relay': typeof PublicSsoRelayRoute
  '/_public/whats-new/$version': typeof PublicWhatsNewVersionRoute
  '/(_authed)/account/': typeof _authedAccountIndexRoute
  '/(_authed)/tasks/': typeof _authedTasksIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/whats-new/': typeof PublicWhatsNewIndexRoute
  '/(_authed)/projects/$slug/settings': typeof _authedProjectsSlugSettingsRouteRouteWithChildren
  '/(_authed)/p/$slug/backlog': typeof _authedPSlugBacklogRoute
  '/(_authed)/p/$slug/epics': typeof _authedPSlugEpicsRoute
  '/(_authed)/p/$slug/members': typeof _authedPSlugMembersRoute
  '/(_authed)/p/$slug/settings': typeof _authedPSlugSettingsRoute
  '/(_authed)/p/$slug/velocity': typeof _authedPSlugVelocityRoute
  '/(_authed)/projects/$slug/backlog': typeof _authedProjectsSlugBacklogRoute
  '/(_authed)/projects/$slug/epics': typeof _authedProjectsSlugEpicsRoute
  '/(_authed)/projects/$slug/members': typeof _authedProjectsSlugMembersRoute
  '/(_authed)/projects/$slug/velocity': typeof _authedProjectsSlugVelocityRoute
  '/_public/auth/atproto/callback': typeof PublicAuthAtprotoCallbackRoute
  '/_public/auth/google/callback': typeof PublicAuthGoogleCallbackRoute
  '/(_authed)/p/$slug/': typeof _authedPSlugIndexRoute
  '/(_authed)/projects/$slug/': typeof _authedProjectsSlugIndexRoute
  '/(_authed)/s/$storyId/': typeof _authedSStoryIdIndexRoute
  '/(_authed)/p/$slug/board/$storyRef': typeof _authedPSlugBoardStoryRefRoute
  '/(_authed)/projects/$slug/board/$storyRef': typeof _authedProjectsSlugBoardStoryRefRoute
  '/(_authed)/projects/$slug/settings/danger': typeof _authedProjectsSlugSettingsDangerRoute
  '/(_authed)/projects/$slug/settings/data': typeof _authedProjectsSlugSettingsDataRoute
  '/(_authed)/projects/$slug/settings/general': typeof _authedProjectsSlugSettingsGeneralRoute
  '/(_authed)/projects/$slug/settings/integrations': typeof _authedProjectsSlugSettingsIntegrationsRoute
  '/(_authed)/projects/$slug/settings/notifications': typeof _authedProjectsSlugSettingsNotificationsRoute
  '/(_authed)/projects/$slug/settings/ownership': typeof _authedProjectsSlugSettingsOwnershipRoute
  '/(_authed)/projects/$slug/settings/webhooks': typeof _authedProjectsSlugSettingsWebhooksRoute
  '/(_authed)/p/$slug/board/': typeof _authedPSlugBoardIndexRoute
  '/(_authed)/projects/$slug/board/': typeof _authedProjectsSlugBoardIndexRoute
  '/(_authed)/projects/$slug/settings/': typeof _authedProjectsSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/dev-token'
    | '/oauth/callback'
    | '/sso/relay'
    | '/whats-new/$version'
    | '/account/'
    | '/tasks/'
    | '/login/'
    | '/whats-new/'
    | '/projects/$slug/settings'
    | '/p/$slug/backlog'
    | '/p/$slug/epics'
    | '/p/$slug/members'
    | '/p/$slug/settings'
    | '/p/$slug/velocity'
    | '/projects/$slug/backlog'
    | '/projects/$slug/epics'
    | '/projects/$slug/members'
    | '/projects/$slug/velocity'
    | '/auth/atproto/callback'
    | '/auth/google/callback'
    | '/p/$slug/'
    | '/projects/$slug/'
    | '/s/$storyId/'
    | '/p/$slug/board/$storyRef'
    | '/projects/$slug/board/$storyRef'
    | '/projects/$slug/settings/danger'
    | '/projects/$slug/settings/data'
    | '/projects/$slug/settings/general'
    | '/projects/$slug/settings/integrations'
    | '/projects/$slug/settings/notifications'
    | '/projects/$slug/settings/ownership'
    | '/projects/$slug/settings/webhooks'
    | '/p/$slug/board/'
    | '/projects/$slug/board/'
    | '/projects/$slug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/dev-token'
    | '/oauth/callback'
    | '/sso/relay'
    | '/whats-new/$version'
    | '/account'
    | '/tasks'
    | '/login'
    | '/whats-new'
    | '/p/$slug/backlog'
    | '/p/$slug/epics'
    | '/p/$slug/members'
    | '/p/$slug/settings'
    | '/p/$slug/velocity'
    | '/projects/$slug/backlog'
    | '/projects/$slug/epics'
    | '/projects/$slug/members'
    | '/projects/$slug/velocity'
    | '/auth/atproto/callback'
    | '/auth/google/callback'
    | '/p/$slug'
    | '/projects/$slug'
    | '/s/$storyId'
    | '/p/$slug/board/$storyRef'
    | '/projects/$slug/board/$storyRef'
    | '/projects/$slug/settings/danger'
    | '/projects/$slug/settings/data'
    | '/projects/$slug/settings/general'
    | '/projects/$slug/settings/integrations'
    | '/projects/$slug/settings/notifications'
    | '/projects/$slug/settings/ownership'
    | '/projects/$slug/settings/webhooks'
    | '/p/$slug/board'
    | '/projects/$slug/board'
    | '/projects/$slug/settings'
  id:
    | '__root__'
    | '/(_authed)'
    | '/(_authed)/'
    | '/_public/auth/dev-token'
    | '/_public/oauth/callback'
    | '/_public/sso/relay'
    | '/_public/whats-new/$version'
    | '/(_authed)/account/'
    | '/(_authed)/tasks/'
    | '/_public/login/'
    | '/_public/whats-new/'
    | '/(_authed)/projects/$slug/settings'
    | '/(_authed)/p/$slug/backlog'
    | '/(_authed)/p/$slug/epics'
    | '/(_authed)/p/$slug/members'
    | '/(_authed)/p/$slug/settings'
    | '/(_authed)/p/$slug/velocity'
    | '/(_authed)/projects/$slug/backlog'
    | '/(_authed)/projects/$slug/epics'
    | '/(_authed)/projects/$slug/members'
    | '/(_authed)/projects/$slug/velocity'
    | '/_public/auth/atproto/callback'
    | '/_public/auth/google/callback'
    | '/(_authed)/p/$slug/'
    | '/(_authed)/projects/$slug/'
    | '/(_authed)/s/$storyId/'
    | '/(_authed)/p/$slug/board/$storyRef'
    | '/(_authed)/projects/$slug/board/$storyRef'
    | '/(_authed)/projects/$slug/settings/danger'
    | '/(_authed)/projects/$slug/settings/data'
    | '/(_authed)/projects/$slug/settings/general'
    | '/(_authed)/projects/$slug/settings/integrations'
    | '/(_authed)/projects/$slug/settings/notifications'
    | '/(_authed)/projects/$slug/settings/ownership'
    | '/(_authed)/projects/$slug/settings/webhooks'
    | '/(_authed)/p/$slug/board/'
    | '/(_authed)/projects/$slug/board/'
    | '/(_authed)/projects/$slug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authedRouteRoute: typeof _authedRouteRouteWithChildren
  PublicAuthDevTokenRoute: typeof PublicAuthDevTokenRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
  PublicSsoRelayRoute: typeof PublicSsoRelayRoute
  PublicWhatsNewVersionRoute: typeof PublicWhatsNewVersionRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicWhatsNewIndexRoute: typeof PublicWhatsNewIndexRoute
  PublicAuthAtprotoCallbackRoute: typeof PublicAuthAtprotoCallbackRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(_authed)': {
      id: '/(_authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authed)/': {
      id: '/(_authed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authedIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/account/': {
      id: '/(_authed)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof _authedAccountIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/tasks/': {
      id: '/(_authed)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof _authedTasksIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/_public/auth/dev-token': {
      id: '/_public/auth/dev-token'
      path: '/auth/dev-token'
      fullPath: '/auth/dev-token'
      preLoaderRoute: typeof PublicAuthDevTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sso/relay': {
      id: '/_public/sso/relay'
      path: '/sso/relay'
      fullPath: '/sso/relay'
      preLoaderRoute: typeof PublicSsoRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/whats-new/': {
      id: '/_public/whats-new/'
      path: '/whats-new'
      fullPath: '/whats-new/'
      preLoaderRoute: typeof PublicWhatsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/whats-new/$version': {
      id: '/_public/whats-new/$version'
      path: '/whats-new/$version'
      fullPath: '/whats-new/$version'
      preLoaderRoute: typeof PublicWhatsNewVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authed)/p/$slug/': {
      id: '/(_authed)/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof _authedPSlugIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/backlog': {
      id: '/(_authed)/p/$slug/backlog'
      path: '/p/$slug/backlog'
      fullPath: '/p/$slug/backlog'
      preLoaderRoute: typeof _authedPSlugBacklogRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/epics': {
      id: '/(_authed)/p/$slug/epics'
      path: '/p/$slug/epics'
      fullPath: '/p/$slug/epics'
      preLoaderRoute: typeof _authedPSlugEpicsRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/members': {
      id: '/(_authed)/p/$slug/members'
      path: '/p/$slug/members'
      fullPath: '/p/$slug/members'
      preLoaderRoute: typeof _authedPSlugMembersRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/settings': {
      id: '/(_authed)/p/$slug/settings'
      path: '/p/$slug/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof _authedPSlugSettingsRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/velocity': {
      id: '/(_authed)/p/$slug/velocity'
      path: '/p/$slug/velocity'
      fullPath: '/p/$slug/velocity'
      preLoaderRoute: typeof _authedPSlugVelocityRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/': {
      id: '/(_authed)/projects/$slug/'
      path: '/projects/$slug'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof _authedProjectsSlugIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/backlog': {
      id: '/(_authed)/projects/$slug/backlog'
      path: '/projects/$slug/backlog'
      fullPath: '/projects/$slug/backlog'
      preLoaderRoute: typeof _authedProjectsSlugBacklogRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/epics': {
      id: '/(_authed)/projects/$slug/epics'
      path: '/projects/$slug/epics'
      fullPath: '/projects/$slug/epics'
      preLoaderRoute: typeof _authedProjectsSlugEpicsRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/members': {
      id: '/(_authed)/projects/$slug/members'
      path: '/projects/$slug/members'
      fullPath: '/projects/$slug/members'
      preLoaderRoute: typeof _authedProjectsSlugMembersRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/settings': {
      id: '/(_authed)/projects/$slug/settings'
      path: '/projects/$slug/settings'
      fullPath: '/projects/$slug/settings'
      preLoaderRoute: typeof _authedProjectsSlugSettingsRouteRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/velocity': {
      id: '/(_authed)/projects/$slug/velocity'
      path: '/projects/$slug/velocity'
      fullPath: '/projects/$slug/velocity'
      preLoaderRoute: typeof _authedProjectsSlugVelocityRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/s/$storyId/': {
      id: '/(_authed)/s/$storyId/'
      path: '/s/$storyId'
      fullPath: '/s/$storyId/'
      preLoaderRoute: typeof _authedSStoryIdIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/_public/auth/atproto/callback': {
      id: '/_public/auth/atproto/callback'
      path: '/auth/atproto/callback'
      fullPath: '/auth/atproto/callback'
      preLoaderRoute: typeof PublicAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/google/callback': {
      id: '/_public/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authed)/p/$slug/board/': {
      id: '/(_authed)/p/$slug/board/'
      path: '/p/$slug/board'
      fullPath: '/p/$slug/board/'
      preLoaderRoute: typeof _authedPSlugBoardIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/p/$slug/board/$storyRef': {
      id: '/(_authed)/p/$slug/board/$storyRef'
      path: '/p/$slug/board/$storyRef'
      fullPath: '/p/$slug/board/$storyRef'
      preLoaderRoute: typeof _authedPSlugBoardStoryRefRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/board/': {
      id: '/(_authed)/projects/$slug/board/'
      path: '/projects/$slug/board'
      fullPath: '/projects/$slug/board/'
      preLoaderRoute: typeof _authedProjectsSlugBoardIndexRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/board/$storyRef': {
      id: '/(_authed)/projects/$slug/board/$storyRef'
      path: '/projects/$slug/board/$storyRef'
      fullPath: '/projects/$slug/board/$storyRef'
      preLoaderRoute: typeof _authedProjectsSlugBoardStoryRefRouteImport
      parentRoute: typeof _authedRouteRoute
    }
    '/(_authed)/projects/$slug/settings/': {
      id: '/(_authed)/projects/$slug/settings/'
      path: '/'
      fullPath: '/projects/$slug/settings/'
      preLoaderRoute: typeof _authedProjectsSlugSettingsIndexRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/danger': {
      id: '/(_authed)/projects/$slug/settings/danger'
      path: '/danger'
      fullPath: '/projects/$slug/settings/danger'
      preLoaderRoute: typeof _authedProjectsSlugSettingsDangerRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/data': {
      id: '/(_authed)/projects/$slug/settings/data'
      path: '/data'
      fullPath: '/projects/$slug/settings/data'
      preLoaderRoute: typeof _authedProjectsSlugSettingsDataRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/general': {
      id: '/(_authed)/projects/$slug/settings/general'
      path: '/general'
      fullPath: '/projects/$slug/settings/general'
      preLoaderRoute: typeof _authedProjectsSlugSettingsGeneralRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/integrations': {
      id: '/(_authed)/projects/$slug/settings/integrations'
      path: '/integrations'
      fullPath: '/projects/$slug/settings/integrations'
      preLoaderRoute: typeof _authedProjectsSlugSettingsIntegrationsRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/notifications': {
      id: '/(_authed)/projects/$slug/settings/notifications'
      path: '/notifications'
      fullPath: '/projects/$slug/settings/notifications'
      preLoaderRoute: typeof _authedProjectsSlugSettingsNotificationsRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/ownership': {
      id: '/(_authed)/projects/$slug/settings/ownership'
      path: '/ownership'
      fullPath: '/projects/$slug/settings/ownership'
      preLoaderRoute: typeof _authedProjectsSlugSettingsOwnershipRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
    '/(_authed)/projects/$slug/settings/webhooks': {
      id: '/(_authed)/projects/$slug/settings/webhooks'
      path: '/webhooks'
      fullPath: '/projects/$slug/settings/webhooks'
      preLoaderRoute: typeof _authedProjectsSlugSettingsWebhooksRouteImport
      parentRoute: typeof _authedProjectsSlugSettingsRouteRoute
    }
  }
}

interface _authedProjectsSlugSettingsRouteRouteChildren {
  _authedProjectsSlugSettingsDangerRoute: typeof _authedProjectsSlugSettingsDangerRoute
  _authedProjectsSlugSettingsDataRoute: typeof _authedProjectsSlugSettingsDataRoute
  _authedProjectsSlugSettingsGeneralRoute: typeof _authedProjectsSlugSettingsGeneralRoute
  _authedProjectsSlugSettingsIntegrationsRoute: typeof _authedProjectsSlugSettingsIntegrationsRoute
  _authedProjectsSlugSettingsNotificationsRoute: typeof _authedProjectsSlugSettingsNotificationsRoute
  _authedProjectsSlugSettingsOwnershipRoute: typeof _authedProjectsSlugSettingsOwnershipRoute
  _authedProjectsSlugSettingsWebhooksRoute: typeof _authedProjectsSlugSettingsWebhooksRoute
  _authedProjectsSlugSettingsIndexRoute: typeof _authedProjectsSlugSettingsIndexRoute
}

const _authedProjectsSlugSettingsRouteRouteChildren: _authedProjectsSlugSettingsRouteRouteChildren =
  {
    _authedProjectsSlugSettingsDangerRoute:
      _authedProjectsSlugSettingsDangerRoute,
    _authedProjectsSlugSettingsDataRoute: _authedProjectsSlugSettingsDataRoute,
    _authedProjectsSlugSettingsGeneralRoute:
      _authedProjectsSlugSettingsGeneralRoute,
    _authedProjectsSlugSettingsIntegrationsRoute:
      _authedProjectsSlugSettingsIntegrationsRoute,
    _authedProjectsSlugSettingsNotificationsRoute:
      _authedProjectsSlugSettingsNotificationsRoute,
    _authedProjectsSlugSettingsOwnershipRoute:
      _authedProjectsSlugSettingsOwnershipRoute,
    _authedProjectsSlugSettingsWebhooksRoute:
      _authedProjectsSlugSettingsWebhooksRoute,
    _authedProjectsSlugSettingsIndexRoute:
      _authedProjectsSlugSettingsIndexRoute,
  }

const _authedProjectsSlugSettingsRouteRouteWithChildren =
  _authedProjectsSlugSettingsRouteRoute._addFileChildren(
    _authedProjectsSlugSettingsRouteRouteChildren,
  )

interface _authedRouteRouteChildren {
  _authedIndexRoute: typeof _authedIndexRoute
  _authedAccountIndexRoute: typeof _authedAccountIndexRoute
  _authedTasksIndexRoute: typeof _authedTasksIndexRoute
  _authedProjectsSlugSettingsRouteRoute: typeof _authedProjectsSlugSettingsRouteRouteWithChildren
  _authedPSlugBacklogRoute: typeof _authedPSlugBacklogRoute
  _authedPSlugEpicsRoute: typeof _authedPSlugEpicsRoute
  _authedPSlugMembersRoute: typeof _authedPSlugMembersRoute
  _authedPSlugSettingsRoute: typeof _authedPSlugSettingsRoute
  _authedPSlugVelocityRoute: typeof _authedPSlugVelocityRoute
  _authedProjectsSlugBacklogRoute: typeof _authedProjectsSlugBacklogRoute
  _authedProjectsSlugEpicsRoute: typeof _authedProjectsSlugEpicsRoute
  _authedProjectsSlugMembersRoute: typeof _authedProjectsSlugMembersRoute
  _authedProjectsSlugVelocityRoute: typeof _authedProjectsSlugVelocityRoute
  _authedPSlugIndexRoute: typeof _authedPSlugIndexRoute
  _authedProjectsSlugIndexRoute: typeof _authedProjectsSlugIndexRoute
  _authedSStoryIdIndexRoute: typeof _authedSStoryIdIndexRoute
  _authedPSlugBoardStoryRefRoute: typeof _authedPSlugBoardStoryRefRoute
  _authedProjectsSlugBoardStoryRefRoute: typeof _authedProjectsSlugBoardStoryRefRoute
  _authedPSlugBoardIndexRoute: typeof _authedPSlugBoardIndexRoute
  _authedProjectsSlugBoardIndexRoute: typeof _authedProjectsSlugBoardIndexRoute
}

const _authedRouteRouteChildren: _authedRouteRouteChildren = {
  _authedIndexRoute: _authedIndexRoute,
  _authedAccountIndexRoute: _authedAccountIndexRoute,
  _authedTasksIndexRoute: _authedTasksIndexRoute,
  _authedProjectsSlugSettingsRouteRoute:
    _authedProjectsSlugSettingsRouteRouteWithChildren,
  _authedPSlugBacklogRoute: _authedPSlugBacklogRoute,
  _authedPSlugEpicsRoute: _authedPSlugEpicsRoute,
  _authedPSlugMembersRoute: _authedPSlugMembersRoute,
  _authedPSlugSettingsRoute: _authedPSlugSettingsRoute,
  _authedPSlugVelocityRoute: _authedPSlugVelocityRoute,
  _authedProjectsSlugBacklogRoute: _authedProjectsSlugBacklogRoute,
  _authedProjectsSlugEpicsRoute: _authedProjectsSlugEpicsRoute,
  _authedProjectsSlugMembersRoute: _authedProjectsSlugMembersRoute,
  _authedProjectsSlugVelocityRoute: _authedProjectsSlugVelocityRoute,
  _authedPSlugIndexRoute: _authedPSlugIndexRoute,
  _authedProjectsSlugIndexRoute: _authedProjectsSlugIndexRoute,
  _authedSStoryIdIndexRoute: _authedSStoryIdIndexRoute,
  _authedPSlugBoardStoryRefRoute: _authedPSlugBoardStoryRefRoute,
  _authedProjectsSlugBoardStoryRefRoute: _authedProjectsSlugBoardStoryRefRoute,
  _authedPSlugBoardIndexRoute: _authedPSlugBoardIndexRoute,
  _authedProjectsSlugBoardIndexRoute: _authedProjectsSlugBoardIndexRoute,
}

const _authedRouteRouteWithChildren = _authedRouteRoute._addFileChildren(
  _authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authedRouteRoute: _authedRouteRouteWithChildren,
  PublicAuthDevTokenRoute: PublicAuthDevTokenRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
  PublicSsoRelayRoute: PublicSsoRelayRoute,
  PublicWhatsNewVersionRoute: PublicWhatsNewVersionRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicWhatsNewIndexRoute: PublicWhatsNewIndexRoute,
  PublicAuthAtprotoCallbackRoute: PublicAuthAtprotoCallbackRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
