/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthDevTokenRouteImport } from './routes/auth/dev-token'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as SsoRelayRouteImport } from './routes/sso/relay'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AuthAtprotoCallbackRouteImport } from './routes/auth/atproto/callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AppPSlugBacklogRouteImport } from './routes/_app/p/$slug/backlog'
import { Route as AppPSlugBoardRouteImport } from './routes/_app/p/$slug/board'
import { Route as AppPSlugEpicsRouteImport } from './routes/_app/p/$slug/epics'
import { Route as AppPSlugMembersRouteImport } from './routes/_app/p/$slug/members'
import { Route as AppPSlugVelocityRouteImport } from './routes/_app/p/$slug/velocity'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthDevTokenRoute = AuthDevTokenRouteImport.update({
  id: '/auth/dev-token',
  path: '/auth/dev-token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRelayRoute = SsoRelayRouteImport.update({
  id: '/sso/relay',
  path: '/sso/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthAtprotoCallbackRoute = AuthAtprotoCallbackRouteImport.update({
  id: '/auth/atproto/callback',
  path: '/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPSlugBacklogRoute = AppPSlugBacklogRouteImport.update({
  id: '/p/$slug/backlog',
  path: '/p/$slug/backlog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugBoardRoute = AppPSlugBoardRouteImport.update({
  id: '/p/$slug/board',
  path: '/p/$slug/board',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugEpicsRoute = AppPSlugEpicsRouteImport.update({
  id: '/p/$slug/epics',
  path: '/p/$slug/epics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugMembersRoute = AppPSlugMembersRouteImport.update({
  id: '/p/$slug/members',
  path: '/p/$slug/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPSlugVelocityRoute = AppPSlugVelocityRouteImport.update({
  id: '/p/$slug/velocity',
  path: '/p/$slug/velocity',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/dev-token': typeof AuthDevTokenRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/sso/relay': typeof SsoRelayRoute
  '/login/': typeof LoginIndexRoute
  '/auth/atproto/callback': typeof AuthAtprotoCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/p/$slug/backlog': typeof AppPSlugBacklogRoute
  '/p/$slug/board': typeof AppPSlugBoardRoute
  '/p/$slug/epics': typeof AppPSlugEpicsRoute
  '/p/$slug/members': typeof AppPSlugMembersRoute
  '/p/$slug/velocity': typeof AppPSlugVelocityRoute
}
export interface FileRoutesByTo {
  '/auth/dev-token': typeof AuthDevTokenRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/sso/relay': typeof SsoRelayRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/auth/atproto/callback': typeof AuthAtprotoCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/tasks': typeof AppTasksIndexRoute
  '/p/$slug/backlog': typeof AppPSlugBacklogRoute
  '/p/$slug/board': typeof AppPSlugBoardRoute
  '/p/$slug/epics': typeof AppPSlugEpicsRoute
  '/p/$slug/members': typeof AppPSlugMembersRoute
  '/p/$slug/velocity': typeof AppPSlugVelocityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/auth/dev-token': typeof AuthDevTokenRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/sso/relay': typeof SsoRelayRoute
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/auth/atproto/callback': typeof AuthAtprotoCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/p/$slug/backlog': typeof AppPSlugBacklogRoute
  '/_app/p/$slug/board': typeof AppPSlugBoardRoute
  '/_app/p/$slug/epics': typeof AppPSlugEpicsRoute
  '/_app/p/$slug/members': typeof AppPSlugMembersRoute
  '/_app/p/$slug/velocity': typeof AppPSlugVelocityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/dev-token'
    | '/oauth/callback'
    | '/sso/relay'
    | '/login/'
    | '/auth/atproto/callback'
    | '/auth/google/callback'
    | '/tasks/'
    | '/p/$slug/backlog'
    | '/p/$slug/board'
    | '/p/$slug/epics'
    | '/p/$slug/members'
    | '/p/$slug/velocity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/dev-token'
    | '/oauth/callback'
    | '/sso/relay'
    | '/'
    | '/login'
    | '/auth/atproto/callback'
    | '/auth/google/callback'
    | '/tasks'
    | '/p/$slug/backlog'
    | '/p/$slug/board'
    | '/p/$slug/epics'
    | '/p/$slug/members'
    | '/p/$slug/velocity'
  id:
    | '__root__'
    | '/_app'
    | '/auth/dev-token'
    | '/oauth/callback'
    | '/sso/relay'
    | '/_app/'
    | '/login/'
    | '/auth/atproto/callback'
    | '/auth/google/callback'
    | '/_app/tasks/'
    | '/_app/p/$slug/backlog'
    | '/_app/p/$slug/board'
    | '/_app/p/$slug/epics'
    | '/_app/p/$slug/members'
    | '/_app/p/$slug/velocity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthDevTokenRoute: typeof AuthDevTokenRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SsoRelayRoute: typeof SsoRelayRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AuthAtprotoCallbackRoute: typeof AuthAtprotoCallbackRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/dev-token': {
      id: '/auth/dev-token'
      path: '/auth/dev-token'
      fullPath: '/auth/dev-token'
      preLoaderRoute: typeof AuthDevTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/relay': {
      id: '/sso/relay'
      path: '/sso/relay'
      fullPath: '/sso/relay'
      preLoaderRoute: typeof SsoRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/atproto/callback': {
      id: '/auth/atproto/callback'
      path: '/auth/atproto/callback'
      fullPath: '/auth/atproto/callback'
      preLoaderRoute: typeof AuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$slug/backlog': {
      id: '/_app/p/$slug/backlog'
      path: '/p/$slug/backlog'
      fullPath: '/p/$slug/backlog'
      preLoaderRoute: typeof AppPSlugBacklogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/board': {
      id: '/_app/p/$slug/board'
      path: '/p/$slug/board'
      fullPath: '/p/$slug/board'
      preLoaderRoute: typeof AppPSlugBoardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/epics': {
      id: '/_app/p/$slug/epics'
      path: '/p/$slug/epics'
      fullPath: '/p/$slug/epics'
      preLoaderRoute: typeof AppPSlugEpicsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/members': {
      id: '/_app/p/$slug/members'
      path: '/p/$slug/members'
      fullPath: '/p/$slug/members'
      preLoaderRoute: typeof AppPSlugMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$slug/velocity': {
      id: '/_app/p/$slug/velocity'
      path: '/p/$slug/velocity'
      fullPath: '/p/$slug/velocity'
      preLoaderRoute: typeof AppPSlugVelocityRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppPSlugBacklogRoute: typeof AppPSlugBacklogRoute
  AppPSlugBoardRoute: typeof AppPSlugBoardRoute
  AppPSlugEpicsRoute: typeof AppPSlugEpicsRoute
  AppPSlugMembersRoute: typeof AppPSlugMembersRoute
  AppPSlugVelocityRoute: typeof AppPSlugVelocityRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppPSlugBacklogRoute: AppPSlugBacklogRoute,
  AppPSlugBoardRoute: AppPSlugBoardRoute,
  AppPSlugEpicsRoute: AppPSlugEpicsRoute,
  AppPSlugMembersRoute: AppPSlugMembersRoute,
  AppPSlugVelocityRoute: AppPSlugVelocityRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthDevTokenRoute: AuthDevTokenRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SsoRelayRoute: SsoRelayRoute,
  LoginIndexRoute: LoginIndexRoute,
  AuthAtprotoCallbackRoute: AuthAtprotoCallbackRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
